# Generated by Django 5.1.6 on 2025-03-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='srnshot',
            new_name='screenshot',
        ),
    ]
