# Generated by Django 5.1.6 on 2025-03-06 14:49

import rewards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_rename_srnshot_screenshot_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot',
            field=models.ImageField(upload_to=rewards.models.user_directory_path),
        ),
    ]
