# Generated by Django 5.1.6 on 2025-03-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_alter_screenshot_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
